src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

student1(menu.jsp) Change favourite link /15

---

src/main/java/acme/entities/risk/Risk.java

feat(entities): Review Risk Entity #103

---

src/main/java/acme/entities/claims/Claim.java

Crated claim entity (with actual content now). Task G03.
Closes #97

Created claim entity.

---

src/main/java/acme/entities/projects/UserStory.java
src/main/java/acme/entities/projects/UserStoryPriority.java
src/main/java/acme/roles/Manager.java

User Story entity created.
UserStoryPriority enum created.
Manager role started but not detailed.
Missing to check that a Project doesn't have UserStories of more than one different Manager.

feat(Projects): User Story entity #113

---

src/main/java/acme/forms/ManagerDashboard.java

Manager Dashboard (form) created.

feat(Forms): Manager Dashboard #114

---

src/main/java/acme/roles/Manager.java

Added a length validation to URL.
Closes #117

fix(Projects): Fix Manager URL length #117

---

src/main/java/acme/entities/projects/Project.java

fix(Projects): Fix Project entity #112

---

src/main/java/acme/entities/audits/Audit.java
src/main/java/acme/entities/audits/AuditType.java
src/main/java/acme/entities/audits/Record.java
src/main/java/acme/forms/AuditorDashboard.java
src/main/java/acme/roles/Auditor.java
src/main/webapp/WEB-INF/views/messages-en.i18n
src/main/webapp/WEB-INF/views/messages-es.i18n

Created audit and record entity, auditor role and auditor dashboard (form), as well as an enum.
#156 #155 #157 #162

Initialize audit tasks.

---

src/main/java/acme/entities/projects/UserStory.java

Solved after client comments.
Closes #113

fix(Projects): Fix User Stroy entity #113

---

src/main/java/acme/entities/audits/Audit.java
src/main/java/acme/entities/audits/AuditRecord.java
src/main/java/acme/entities/audits/Mark.java

Added the mark custom enum and relationships between entities.

Individual work: added marks and relationships.

---

src/main/webapp/WEB-INF/resources/sample-data/manager.csv
src/main/webapp/WEB-INF/resources/sample-data/project.csv
src/main/webapp/WEB-INF/resources/sample-data/user-account.csv
src/main/webapp/WEB-INF/resources/sample-data/user-story.csv

Includes sample data for manager, project, user stories. More user accounts have been created.
Closes #116

feat(Projects): Sample data for projects entities #116

---

src/main/java/acme/entities/audits/AuditRecord.java
src/main/java/acme/entities/audits/Mark.java
src/main/webapp/WEB-INF/resources/sample-data/audit-record.csv
src/main/webapp/WEB-INF/resources/sample-data/audit.csv
src/main/webapp/WEB-INF/resources/sample-data/auditor.csv
src/main/webapp/WEB-INF/resources/sample-data/user-account.csv

Added sample data for audits, created auditor accounts.

Individual work: sample data for audits and account creation.

---

src/main/webapp/WEB-INF/resources/sample-data/project.csv
src/main/webapp/WEB-INF/resources/sample-data/user-story.csv

fix(Projects): Fixed sample data descriptions #116

---

src/main/webapp/WEB-INF/resources/sample-data/manager.csv
src/main/webapp/WEB-INF/resources/sample-data/project.csv
src/main/webapp/WEB-INF/resources/sample-data/user-account.csv
src/main/webapp/WEB-INF/resources/sample-data/user-story.csv

Feature/populate projects/116

---

src/main/java/acme/entities/sponsorships/Invoice.java
src/main/java/acme/entities/sponsorships/Sponsorship.java
src/main/webapp/WEB-INF/resources/sample-data/banner.csv

feat(Banner): Sample Data #134

---

src/main/java/acme/entities/configuration/Configuration.java
src/main/webapp/WEB-INF/resources/initial-data/configuration.csv
src/main/webapp/WEB-INF/views/messages-en.i18n
src/main/webapp/WEB-INF/views/messages-es.i18n

Created system currency configuration. Group task number 21.
Closes #89

REVIEW: Create system currency configuration.

---

src/main/java/acme/forms/ManagerDashboard.java
src/main/webapp/WEB-INF/resources/sample-data/project.csv
src/main/webapp/WEB-INF/resources/sample-data/user-account.csv
src/main/webapp/WEB-INF/resources/sample-data/user-story.csv

fix(Projects): Updated population #116

---

src/main/java/acme/entities/audits/AuditRecord.java
src/main/java/acme/entities/audits/CodeAudit.java
src/main/java/acme/forms/AuditorDashboard.java

Individual work: Fix annotations.

---

src/main/webapp/WEB-INF/resources/sample-data/audit-record.csv
src/main/webapp/WEB-INF/resources/sample-data/code-audit.csv

Added extra data according to the discussion post.

Individual work: Add extra data.

---

src/main/webapp/WEB-INF/resources/sample-data/claim.csv

Data fixes according to post in discussion board.

Fix: extra claim data added.

---

src/main/java/acme/forms/AdministratorDashboard.java
src/main/java/acme/forms/ClientDashboard.java

feat(AdministratorDashboard) Create administrator dashboard #92

---

reports/Student #5/UML_Student5.uxf

docs(uml): update uml

---

src/main/java/acme/features/any/claim/AnyClaimController.java
src/main/java/acme/features/any/claim/AnyClaimCreateService.java
src/main/java/acme/features/any/claim/AnyClaimListService.java
src/main/java/acme/features/any/claim/AnyClaimRepository.java
src/main/java/acme/features/any/claim/AnyClaimShowService.java
src/main/webapp/WEB-INF/views/any/claim/form.jsp
src/main/webapp/WEB-INF/views/any/claim/list.jsp
src/main/webapp/WEB-INF/views/any/claim/messages-en.i18n
src/main/webapp/WEB-INF/views/any/claim/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp
src/main/webapp/WEB-INF/views/messages-en.i18n
src/main/webapp/WEB-INF/views/messages-es.i18n

Added claim operations: list, show, create (publish).

Group task: add claim operations.

---

src/main/java/acme/features/authenticated/risk/AuthenticatedRiskController.java
src/main/java/acme/features/authenticated/risk/AuthenticatedRiskListService.java
src/main/java/acme/features/authenticated/risk/AuthenticatedRiskRepository.java
src/main/java/acme/features/authenticated/risk/AuthenticatedRiskShowService.java
src/main/webapp/WEB-INF/views/authenticated/risk/form.jsp
src/main/webapp/WEB-INF/views/authenticated/risk/list.jsp
src/main/webapp/WEB-INF/views/authenticated/risk/messages-en.i18n
src/main/webapp/WEB-INF/views/authenticated/risk/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

feat(Authenticated): List and show Risks #295

---

src/main/webapp/WEB-INF/views/any/claim/form.jsp
src/main/webapp/WEB-INF/views/any/claim/messages-en.i18n
src/main/webapp/WEB-INF/views/any/claim/messages-es.i18n

fix(claim): add missing attribute to show

---

src/main/java/acme/features/administrator/risk/AdministratorRiskController.java
src/main/java/acme/features/administrator/risk/AdministratorRiskCreateService.java
src/main/java/acme/features/administrator/risk/AdministratorRiskDeleteService.java
src/main/java/acme/features/administrator/risk/AdministratorRiskListService.java
src/main/java/acme/features/administrator/risk/AdministratorRiskRepository.java
src/main/java/acme/features/administrator/risk/AdministratorRiskShowService.java
src/main/java/acme/features/administrator/risk/AdministratorRiskUpdateService.java
src/main/java/acme/features/manager/project/ManagerProjectCreateService.java
src/main/java/acme/features/manager/project/ManagerProjectRepository.java
src/main/java/acme/features/manager/project/ManagerProjectUpdateService.java
src/main/webapp/WEB-INF/views/administrator/risk/form.jsp
src/main/webapp/WEB-INF/views/administrator/risk/list.jsp
src/main/webapp/WEB-INF/views/administrator/risk/messages-en.i18n
src/main/webapp/WEB-INF/views/administrator/risk/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp
src/main/webapp/WEB-INF/views/manager/project/messages-en.i18n
src/main/webapp/WEB-INF/views/manager/project/messages-es.i18n

Feature/risk ops admins/296 after review

---

src/main/java/acme/features/administrator/banner/AdministratorBannerController.java
src/main/java/acme/features/administrator/banner/AdministratorBannerCreateService.java
src/main/java/acme/features/administrator/banner/AdministratorBannerDeleteService.java
src/main/java/acme/features/administrator/banner/AdministratorBannerListAllService.java
src/main/java/acme/features/administrator/banner/AdministratorBannerRepository.java
src/main/java/acme/features/administrator/banner/AdministratorBannerShowService.java
src/main/java/acme/features/administrator/banner/AdministratorBannerUpdateService.java
src/main/webapp/WEB-INF/views/administrator/banner/form.jsp
src/main/webapp/WEB-INF/views/administrator/banner/list.jsp
src/main/webapp/WEB-INF/views/administrator/banner/messages-en.i18n
src/main/webapp/WEB-INF/views/administrator/banner/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp
src/main/webapp/WEB-INF/views/manager/project/form.jsp

feat(Banner): CRUD Operations #302

---

src/main/java/acme/features/any/project/AnyProjectController.java
src/main/java/acme/features/any/project/AnyProjectListService.java
src/main/java/acme/features/any/project/AnyProjectRepository.java
src/main/java/acme/features/any/project/AnyProjectShowService.java
src/main/webapp/WEB-INF/views/administrator/risk/messages-en.i18n
src/main/webapp/WEB-INF/views/administrator/risk/messages-es.i18n
src/main/webapp/WEB-INF/views/any/project/form.jsp
src/main/webapp/WEB-INF/views/any/project/list.jsp
src/main/webapp/WEB-INF/views/any/project/messages-en.i18n
src/main/webapp/WEB-INF/views/any/project/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp
src/main/webapp/WEB-INF/views/manager/project/form.jsp
src/main/webapp/WEB-INF/views/manager/project/messages-en.i18n
src/main/webapp/WEB-INF/views/manager/project/messages-es.i18n

feat(Any): List and show project #273

---

src/main/java/acme/features/administrator/risk/AdministratorRiskShowService.java
src/main/java/acme/features/administrator/risk/AdministratorRiskUpdateService.java
src/main/webapp/WEB-INF/views/administrator/risk/form.jsp

fix(Admin): Derived value of Risk form

---

src/main/webapp/WEB-INF/views/manager/user-account/form.jsp
src/main/webapp/WEB-INF/views/manager/user-account/messages-en.i18n
src/main/webapp/WEB-INF/views/manager/user-account/messages-es.i18n

feat(Manager): Update profile #272

---

src/main/java/acme/features/authenticated/manager/AuthenticatedManagerController.java
src/main/java/acme/features/authenticated/manager/AuthenticatedManagerRepository.java
src/main/java/acme/features/authenticated/manager/AuthenticatedManagerUpdateService.java
src/main/webapp/WEB-INF/views/administrator/risk/messages-es.i18n
src/main/webapp/WEB-INF/views/authenticated/manager/messages-es.i18n
src/main/webapp/WEB-INF/views/authenticated/risk/messages-en.i18n
src/main/webapp/WEB-INF/views/authenticated/risk/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp
src/main/webapp/WEB-INF/views/manager/user-story/messages-es.i18n

Old implementation was deleted in branch 271 to implement the sign up.

fix(Manager): Update profile + small fixes #272

---

src/main/webapp/WEB-INF/views/manager/manager-dashboard/form.jsp

Null values will have placeholder "--".

fix(Manager): Placeholder for dashboard

---

src/main/java/acme/features/administrator/banner/AdministratorBannerCreateService.java
src/main/java/acme/features/administrator/banner/AdministratorBannerUpdateService.java
src/main/webapp/WEB-INF/views/administrator/banner/form.jsp
src/main/webapp/WEB-INF/views/administrator/banner/messages-en.i18n
src/main/webapp/WEB-INF/views/administrator/banner/messages-es.i18n

fix(Banner): Operations by Admin #303

---

src/main/java/acme/features/administrator/configuration/AdministratorConfigurationController.java
src/main/java/acme/features/administrator/configuration/AdministratorConfigurationRepository.java
src/main/java/acme/features/administrator/configuration/AdministratorConfigurationShowService.java
src/main/java/acme/features/administrator/configuration/AdministratorConfigurationUpdateService.java
src/main/webapp/WEB-INF/views/administrator/configuration/form.jsp
src/main/webapp/WEB-INF/views/administrator/configuration/messages-en.i18n
src/main/webapp/WEB-INF/views/administrator/configuration/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

• Show the system configuration.
• Update the system configuration.

Extra Task G26: System configuration operations by administrators.

---

src/main/java/acme/features/auditor/auditRecord/AuditorAuditRecordCreateService.java
src/main/java/acme/features/auditor/auditRecord/AuditorAuditRecordDeleteService.java
src/main/java/acme/features/auditor/auditRecord/AuditorAuditRecordPublishService.java
src/main/java/acme/features/auditor/auditRecord/AuditorAuditRecordRepository.java
src/main/java/acme/features/auditor/auditRecord/AuditorAuditRecordShowService.java
src/main/java/acme/features/auditor/auditRecord/AuditorAuditRecordUpdateService.java
src/main/java/acme/features/auditor/auditorDashboard/AuditorDashboardShowService.java
src/main/webapp/WEB-INF/resources/sample-data/code-audit.csv

Small bug fixes for follow-up.

---

src/main/java/acme/features/any/claim/AnyClaimCreateService.java
src/main/java/acme/features/any/claim/AnyClaimRepository.java
src/main/java/acme/features/auditor/auditRecord/AuditorAuditRecordCreateService.java
src/main/java/acme/features/auditor/codeAudit/AuditorCodeAuditCreateService.java
src/main/java/acme/features/auditor/codeAudit/AuditorCodeAuditPublishService.java
src/main/java/acme/features/auditor/codeAudit/AuditorCodeAuditRepository.java
src/main/java/acme/features/auditor/codeAudit/AuditorCodeAuditUpdateService.java
src/main/java/acme/features/authenticated/auditor/AuthenticatedAuditorCreateService.java
src/main/java/acme/features/authenticated/auditor/AuthenticatedAuditorRepository.java
src/main/java/acme/features/authenticated/auditor/AuthenticatedAuditorUpdateService.java
src/main/webapp/WEB-INF/views/any/claim/messages-en.i18n
src/main/webapp/WEB-INF/views/any/claim/messages-es.i18n
src/main/webapp/WEB-INF/views/auditor/code-audit/messages-en.i18n
src/main/webapp/WEB-INF/views/auditor/code-audit/messages-es.i18n
src/main/webapp/WEB-INF/views/authenticated/auditor/messages-en.i18n
src/main/webapp/WEB-INF/views/authenticated/auditor/messages-es.i18n

Spam detector implemented in both individual and group features.

feat(spam): spam implemented in features
